// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: internal/proto/sensordata.proto

package sensordata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Data sample for a single sensor
type SensorData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // timestamp with sub-second precision
	SensorId      uint32                 `protobuf:"varint,3,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	Value         float32                `protobuf:"fixed32,4,opt,name=value,proto3" json:"value,omitempty"`
	Metadata      string                 `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorData) Reset() {
	*x = SensorData{}
	mi := &file_internal_proto_sensordata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorData) ProtoMessage() {}

func (x *SensorData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sensordata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorData.ProtoReflect.Descriptor instead.
func (*SensorData) Descriptor() ([]byte, []int) {
	return file_internal_proto_sensordata_proto_rawDescGZIP(), []int{0}
}

func (x *SensorData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SensorData) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SensorData) GetSensorId() uint32 {
	if x != nil {
		return x.SensorId
	}
	return 0
}

func (x *SensorData) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *SensorData) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

var File_internal_proto_sensordata_proto protoreflect.FileDescriptor

const file_internal_proto_sensordata_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/proto/sensordata.proto\x12\n" +
	"sensordata\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa5\x01\n" +
	"\n" +
	"SensorData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1b\n" +
	"\tsensor_id\x18\x03 \x01(\rR\bsensorId\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x02R\x05value\x12\x1a\n" +
	"\bmetadata\x18\x05 \x01(\tR\bmetadataB&Z$blink-yadp/internal/proto;sensordatab\x06proto3"

var (
	file_internal_proto_sensordata_proto_rawDescOnce sync.Once
	file_internal_proto_sensordata_proto_rawDescData []byte
)

func file_internal_proto_sensordata_proto_rawDescGZIP() []byte {
	file_internal_proto_sensordata_proto_rawDescOnce.Do(func() {
		file_internal_proto_sensordata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_sensordata_proto_rawDesc), len(file_internal_proto_sensordata_proto_rawDesc)))
	})
	return file_internal_proto_sensordata_proto_rawDescData
}

var file_internal_proto_sensordata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_proto_sensordata_proto_goTypes = []any{
	(*SensorData)(nil),            // 0: sensordata.SensorData
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_internal_proto_sensordata_proto_depIdxs = []int32{
	1, // 0: sensordata.SensorData.timestamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_sensordata_proto_init() }
func file_internal_proto_sensordata_proto_init() {
	if File_internal_proto_sensordata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_sensordata_proto_rawDesc), len(file_internal_proto_sensordata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_sensordata_proto_goTypes,
		DependencyIndexes: file_internal_proto_sensordata_proto_depIdxs,
		MessageInfos:      file_internal_proto_sensordata_proto_msgTypes,
	}.Build()
	File_internal_proto_sensordata_proto = out.File
	file_internal_proto_sensordata_proto_goTypes = nil
	file_internal_proto_sensordata_proto_depIdxs = nil
}
